config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get '/about', to: 'static_pages#about'

  resources :lists
  # root "lists#index"
  # resources :lists


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def edit
    @list = List.find(params[:id])
  end

  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def update
    @list = List.find(params[:id])

    if @list.update(list_params)
      redirect_to list_path(@list)
    else
      render :edit
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:chore, :description)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
<h1> Edit Chore </h1>
<%= form_for @list do |f| %>
  <%= f.label :chore %>
  <%= f.text_field :chore %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.submit %>
<% end %>

app/views/lists/index.html.erb
<h1>To Do List</h1>
<p><%= link_to 'New Chores', new_list_path %></p>
<% @lists.each do |list| %>
  <h2><%= list.chore %></h2>
  <!-- <h3><%= list.description %></h3> -->
  <%= link_to 'Edit Chores', edit_list_path(list)%>
  <%= link_to 'Remove Chore', list_path(list), method: :delete %>
  <%= link_to 'Show Chore', list_path(list) %>
<% end %>

app/views/lists/new.html.erb
<h1> New Chore </h1>
<%= form_for @list do |f| %>
  <%= f.label :chore %>
  <%= f.text_field :chore %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.submit %>
<% end %>

app/views/lists/show.html.erb
<h1>List</h1>
<h2><%= @list.chore %></h2>
<p><%= @list.description %></p>
<%= link_to 'Back', lists_path %>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
<h1>Welcome to your chore tracker</h1>
<%=link_to "Your Chore List", lists_path %>